version: '3.8'
services:
  api.booking.local:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      no_cache: true
    stdin_open: true
    tty: true
    volumes:
      - ./data:/usr/src/app/data
      - ./prisma:/usr/src/app/prisma
      - ./src:/usr/src/app/src
    expose:
      - '3001'
    ports:
      - '3001:3001'
    networks:
      booking:
        aliases:
          - api
    env_file:
      - .env
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=${DATABASE_URL}
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 2G

  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      booking:
        aliases:
          - postgres
  redis:
    image: redis:7.0.9-alpine3.17
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres-data:
  redis:
    driver: local

networks:
  booking:
    name: booking
    driver: bridge
